include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
        TimeZone \
        Volumes \
        FileSystem \
        ModifierKeys \
        Defaults

-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble

